//---------------------------------
// Provides Text for Winsock Errors
//---------------------------------

#include <winsock.h>

static struct {
  int   WSErrorCode;
  char* ErrorText;
 } SocErrorTbl[] = {
  { WSAEINTR,"WSAEINTR" },
  { WSAEBADF,"WSAEBADF" },
  { WSAEACCES,"WSAEACCES" },
  { WSAEFAULT,"WSAEFAULT" },
  { WSAEINVAL,"WSAEINVAL" },
  { WSAEMFILE,"WSAEMFILE" },
  { WSAEWOULDBLOCK,"WSAEWOULDBLOCK" },
  { WSAEINPROGRESS,"WSAEINPROGRESS" },
  { WSAEALREADY,"WSAEALREADY" },
  { WSAENOTSOCK,"WSAENOTSOCK" },
  { WSAEDESTADDRREQ,"WSAEDESTADDRREQ" },
  { WSAEMSGSIZE,"WSAEMSGSIZE" },
  { WSAEPROTOTYPE,"WSAEPROTOTYPE" },
  { WSAENOPROTOOPT,"WSAENOPROTOOPT" },
  { WSAEPROTONOSUPPORT,"WSAEPROTONOSSUPORT" },
  { WSAESOCKTNOSUPPORT,"WSAESOCKNOSUPPORT" },
  { WSAEOPNOTSUPP,"WSAEOPNOTSUPP" },
  { WSAEPFNOSUPPORT,"WSAEPFNOSSUPORT" },
  { WSAEAFNOSUPPORT,"WSAEFNOSUPPORT" },
  { WSAEADDRINUSE,"WSAEADDRINUSE" },
  { WSAEADDRNOTAVAIL,"WSAEADDRNOTAVAIL" },
  { WSAENETDOWN,"WSAENETDOWN" },
  { WSAENETUNREACH,"WSAENETUNREACH" },
  { WSAENETRESET,"WASENETRESET" },
  { WSAECONNABORTED,"WSAECONNABORTED" },
  { WSAECONNRESET,"WSAECONNRESET" },
  { WSAENOBUFS,"WSAENOBUFS" },
  { WSAEISCONN,"WSAEISCONN" },
  { WSAENOTCONN,"WSAENOTCONN" },
  { WSAESHUTDOWN,"WSAESHUTDOWN" },
  { WSAETOOMANYREFS,"WSAETOOMANYREFS" },
  { WSAETIMEDOUT,"WSAETIMEDOUT" },
  { WSAECONNREFUSED,"WSAECONNREFUSED" },
  { WSAELOOP,"WSAELOOP" },
  { WSAENAMETOOLONG,"WSAENAMETOOLONG" },
  { WSAEHOSTDOWN,"WSAEHOSTDOWN" },
  { WSAEHOSTUNREACH,"WSAEHOSTUNREACH" },
  { WSAENOTEMPTY,"WSAENOTEMPTY" },
  { WSAEPROCLIM,"WSAEPROCLIM" },
  { WSAEUSERS,"WSAEUSERS" },
  { WSAEDQUOT,"WSAEDQUOT" },
  { WSAESTALE,"WSAESTALE" },
  { WSAEREMOTE,"WSAREMOTE" },
  { WSAEDISCON,"WSAEDISCON" },
  { WSASYSNOTREADY,"WSASYSNOTREADY" },
  { WSAVERNOTSUPPORTED,"WSAVERNOTSUPPORTED" },
  { WSANOTINITIALISED,"WSANOTINITIALISED" },
  { WSAHOST_NOT_FOUND,"WSAHOST_NOT_FOUND" },
  { WSATRY_AGAIN,"WSATRY_AGAIN" },
  { WSANO_RECOVERY,"WSANO_RECOVERY" },
  { WSANO_DATA,"WSANO_DATA" },
  { -1, "UNRECOGNIZED" } };

char* SocStrerror(int WSAErrnum)
{
 register i;
 for (i=0; SocErrorTbl[i].WSErrorCode != WSAErrnum &&
           SocErrorTbl[i].WSErrorCode != -1; ++i);

 return SocErrorTbl[i].ErrorText;
}
