#ifndef __TRANTYPE_H
#define __TRANTYPE_H
#define T_GETLIST            "GLIST"
#define T_PUTLIST            "PLIST"
#define T_GETAUTHRULES       "ARGET"
#define T_PUTAUTHRULES       "ARPUT"
#define T_GETUNVFUNDSRULES   "UVGET"
#define T_PUTUNVFUNDSRULES   "UVPUT"
#define T_GETPOSFILERULES    "PFGET"
#define T_PUTPOSFILERULES    "PFPUT"
#define T_GETDATAREQ         "DQGET"
#define T_PUTDATAREQ         "DQPUT"
#define T_GETPOSRESPONSEREC  "PTGET"
#define T_PUTPOSRESPONSEREC  "PTPUT"
#define T_GETPOSRESPONSETEXT "PTEXT"
#define T_ADMINMSG           "ADMIN"
#define T_VOICEAUTH          "VAUTH"
#define T_VOICEREQ           "VAUTH"
#define T_VOICEREPLY         "VAUTH"
#define T_POSAUTH            "PAUTH"
#define T_GETMERCHANTREC     "MEGET"
#define T_PUTMERCHANTREC     "MEPUT"
#define T_GETREFERRAL        "RQGET"
#define T_PUTREFERRAL        "RQPUT"
#define T_GETPREAUTHS        "PAGET"
#define T_DOPREAUTH          "PREDO"
#define T_FORCEPREAUTH       "PAFOR"
#define T_DOPOSTAUTH         "PSADO"
#define T_AUTHREPLY          "ARPLY"
#define T_DBSEARCH           "DBSCH"
#define T_DBNEXT             "DBNXT"
#define T_DBPREV             "DBPRV"
#define T_GETRECORD          "GETRE"
#define T_ADDRECORD          "ADDRE"
#define T_CHANGERECORD       "CHGRE"
#define T_DELETERECORD       "DELRE"
#define T_POSFILEUPDATE      "POSUP"
#endif
