/****************************************************************************


CheckAuth.rc

produced by Borland Resource Workshop


*****************************************************************************/

#include "CheckAuth.rh"

IDD_CHKAUTH DIALOG 0, 60, 422, 180
STYLE DS_ABSALIGN | DS_3DLOOK | WS_POPUP
CAPTION ""
FONT 8, "MS Sans Serif"
{
 CONTROL "", IDC_MERCHNUM, "static", SS_LEFT | WS_CHILD | WS_VISIBLE | WS_BORDER | WS_TABSTOP, 52, 12, 43, 13
 CONTROL "", IDC_AMOUNT, "static", SS_LEFT | WS_CHILD | WS_VISIBLE | WS_BORDER | WS_TABSTOP, 147, 12, 36, 13
 CONTROL "ComboBox2", IDC_CHECKTYPE, "combobox", CBS_DROPDOWNLIST | WS_CHILD | WS_VISIBLE | WS_TABSTOP, 228, 12, 44, 38
 CONTROL "", IDC_LICENSESTATE, "static", SS_LEFT | ES_UPPERCASE | WS_CHILD | WS_VISIBLE | WS_BORDER | WS_TABSTOP, 52, 33, 15, 13
 CONTROL "", IDC_LICENSE, "static", SS_LEFT | ES_UPPERCASE | WS_CHILD | WS_VISIBLE | WS_BORDER | WS_TABSTOP, 88, 33, 84, 13
 CONTROL "", IDC_DOB, "static", SS_LEFT | WS_CHILD | WS_VISIBLE | WS_BORDER | WS_TABSTOP, 204, 33, 36, 13
 CONTROL "", IDC_CHECKNUMBER, "static", SS_LEFT | ES_NUMBER | WS_CHILD | WS_VISIBLE | WS_BORDER | WS_TABSTOP, 296, 33, 32, 13
 CONTROL "", IDC_ABA, "static", SS_LEFT | ES_NUMBER | WS_CHILD | WS_VISIBLE | WS_BORDER | WS_TABSTOP, 32, 52, 41, 13
 CONTROL "", IDC_ACCOUNT, "static", SS_LEFT | ES_NUMBER | WS_CHILD | WS_VISIBLE | WS_BORDER | WS_TABSTOP, 74, 52, 70, 13, 0
 CONTROL "", IDC_NAME, "static", SS_LEFT | ES_AUTOHSCROLL | ES_UPPERCASE | WS_CHILD | WS_VISIBLE | WS_BORDER | WS_TABSTOP, 173, 52, 93, 13
 CONTROL "ComboBox5", IDC_TITLE, "combobox", CBS_DROPDOWNLIST | CBS_SORT | WS_CHILD | WS_VISIBLE | WS_TABSTOP, 300, 51, 32, 40, 0
 CONTROL "", IDC_ADDRESS, "static", SS_LEFT | ES_AUTOHSCROLL | ES_UPPERCASE | WS_CHILD | WS_VISIBLE | WS_BORDER | WS_TABSTOP, 5, 95, 200, 13
 CONTROL "", IDC_CITY, "static", SS_LEFT | ES_UPPERCASE | WS_CHILD | WS_VISIBLE | WS_BORDER | WS_TABSTOP, 22, 119, 64, 13
 CONTROL "", IDC_CONSUMERSTATE, "static", SS_LEFT | ES_UPPERCASE | WS_CHILD | WS_VISIBLE | WS_BORDER | WS_TABSTOP, 118, 119, 15, 13
 CONTROL "", IDC_ZIPCODE, "static", SS_LEFT | ES_UPPERCASE | WS_CHILD | WS_VISIBLE | WS_BORDER | WS_TABSTOP, 154, 119, 44, 13
 CONTROL "", IDC_APARTMENT, "combobox", CBS_DROPDOWNLIST | WS_CHILD | WS_VISIBLE | WS_TABSTOP, 24, 142, 32, 40, 0
 CONTROL "", IDC_PHONE, "static", SS_LEFT | ES_NUMBER | WS_CHILD | WS_VISIBLE | WS_BORDER | WS_TABSTOP, 92, 142, 45, 13
 CONTROL "", IDC_SSN, "static", SS_LEFT | ES_NUMBER | WS_CHILD | WS_VISIBLE | WS_BORDER | WS_TABSTOP, 160, 142, 44, 14
 CONTROL "", IDC_PRODUCTCLASS, "combobox", CBS_DROPDOWNLIST | WS_CHILD | WS_VISIBLE | WS_VSCROLL | WS_TABSTOP, 272, 82, 120, 100
 CONTROL "", IDC_TRANSPORTMETHOD, "combobox", CBS_DROPDOWNLIST | WS_CHILD | WS_VISIBLE | WS_TABSTOP, 272, 104, 44, 32
 CONTROL "", IDC_BUSINESSNAME, "static", SS_LEFT | ES_AUTOHSCROLL | ES_UPPERCASE | WS_CHILD | WS_VISIBLE | WS_BORDER | WS_TABSTOP, 272, 124, 84, 14
 CONTROL "", IDC_PRIVATELABEL, "combobox", CBS_DROPDOWNLIST | WS_CHILD | WS_VISIBLE | WS_TABSTOP, 272, 146, 32, 36
 CONTROL "MERCHANT", IDCS_MERCHNUM, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 4, 12, 44, 8
 CONTROL "AMOUNT", IDCS_AMOUNT, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 108, 12, 32, 8
 CONTROL "TYPE", IDCS_CHECKTYPE, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 197, 12, 20, 8
 CONTROL "CHECK NUMBER", IDCS_CHECKNUMBER, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 256, 33, 36, 17
 CONTROL "STATE", IDCS_LICENSESTATE, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 20, 33, 28, 14
 CONTROL "D/L", IDCS_LICENSE, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 72, 33, 16, 14
 CONTROL "DOB", IDCS_DOB, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 180, 33, 16, 14
 CONTROL "MICR", IDCS_MICR, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 9, 52, 21, 9
 CONTROL "NAME", IDCS_NAME, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 147, 52, 24, 13
 CONTROL "SSN", IDCS_SSN, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 140, 142, 16, 14
 CONTROL "PHONE", IDCS_PHONE, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 60, 142, 24, 14
 CONTROL "PRODUCT CLASS", IDCS_PRODUCTCLASS, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 224, 82, 36, 17
 CONTROL "ADDRESS", IDCS_ADDRESS, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 8, 82, 36, 10
 CONTROL "CITY", IDCS_CITY, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 2, 119, 20, 13
 CONTROL "STATE", IDCS_CONSUMERSTATE, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 90, 119, 28, 13
 CONTROL "ZIP", IDCS_ZIP, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 138, 119, 16, 13
 CONTROL "APT", IDCS_APARTMENT, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 4, 142, 20, 12
 CONTROL "TRANSPORT", IDCS_TRANSPORT, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 220, 104, 48, 14
 CONTROL "PRIVATE LABEL?", IDCS_PRIVATELABEL, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 236, 146, 32, 17
 CONTROL "BUSINESS NAME", IDCS_BUSINESSNAME, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 224, 124, 40, 17
 CONTROL "Frame1", -1, "static", SS_ETCHEDFRAME | WS_CHILD | WS_VISIBLE, 12, 72, 344, 4
 CONTROL "Frame2", -1, "static", SS_ETCHEDFRAME | WS_CHILD | WS_VISIBLE, 208, 80, 4, 87
 CONTROL "TITLE", IDCS_TITLE, "static", SS_LEFT | WS_CHILD | WS_VISIBLE, 274, 52, 23, 13, 0
}

