#ifndef __CHECKAUTHFN_H
#define __CHECKAUTHFN_H

// These are field number definitions for the Check Authorization
// Message.
//
// There are gaps in the number assignments due to a scheme of
// reserved groups of field numbers that never happened.
//
// There is no such scheme and all the field numbers can be safely
// assigned.

#define FN_TRANTYPE (FLDNUM) 253
#define FN_ADMINMSG (FLDNUM) 254
#define FN_DEBUG (FLDNUM) 255

#define FN_MERCHID (FLDNUM) 0
#define FN_AMOUNT (FLDNUM) 1
#define FN_CHECKTYPE (FLDNUM) 2
#define FN_LICENSESTATE (FLDNUM) 3
#define FN_LICENSE (FLDNUM) 4
#define FN_DOB (FLDNUM) 5
#define FN_CHECKNUMBER (FLDNUM) 6
#define FN_UNUSED7 (FLDNUM) 7
#define FN_CONSUMERNAME (FLDNUM) 8
#define FN_ADDRESS (FLDNUM) 10
#define FN_APARTMENT (FLDNUM) 11
#define FN_CITY (FLDNUM) 12
#define FN_CONSUMERSTATE (FLDNUM) 13
#define FN_ZIPCODE (FLDNUM) 14
#define FN_AREACODE (FLDNUM) 15
#define FN_PHONE (FLDNUM) 16
#define FN_SSN (FLDNUM) 17
#define FN_PRODUCTCLASS (FLDNUM) 18
#define FN_TRANSPORTMETHOD (FLDNUM) 19
#define FN_BUSINESSNAME (FLDNUM) 20
#define FN_PRIVATELABEL (FLDNUM) 21
#define FN_TITLE (FLDNUM) 22

#define FN_AMOUNTROUNDED (FLDNUM) 64
#define FN_CONSUMERAGE (FLDNUM) 65
#define FN_TIMESTAMP (FLDNUM) 66
#define FN_REFERRALNUM (FLDNUM) 67
#define FN_DBRESULT (FLDNUM) 68
#define FN_DBLISTINFO (FLDNUM) 69
#define FN_DBLIST (FLDNUM) 70
#define FN_DBKEY (FLDNUM) 71
#define FN_TEXTRESPONSE (FLDNUM) 72
#define FN_TERMINFO (FLDNUM) 73
#define FN_AUTHRULES (FLDNUM) 74
#define FN_GLOBALAUTHRULES (FLDNUM) 75
#define FN_CLASSAUTHRULES (FLDNUM) 76
#define FN_SUBCLASSAUTHRULES (FLDNUM) 77
#define FN_DATAREQRECORD (FLDNUM) 78
#define FN_UNVFUNDSRULESRECORD (FLDNUM) 79
#define FN_MERCHANTRECORD (FLDNUM) 80
#define FN_ACCOUNTRECORD (FLDNUM) 81
#define FN_ACTIVITY (FLDNUM) 82
#define FN_BADCHECKS (FLDNUM) 83
#define FN_RCODES (FLDNUM) 84
#define FN_RCODE (FLDNUM) 85
#define FN_APPROVALNUM (FLDNUM) 86
#define FN_SOURCETYPE (FLDNUM) 87
#define FN_POSRESPONSERECORD (FLDNUM) 88
#define FN_PREAUTHRECORDS (FLDNUM) 89
#define FN_KWFLD1 (FLDNUM) 90
#define FN_KWFLD2 (FLDNUM) 91
#define FN_KWFLD3 (FLDNUM) 92
#define FN_KWFLD4 (FLDNUM) 93
#define FN_KWFLD5 (FLDNUM) 94
#define FN_CHECKSWIPE (FLDNUM) 95
#define FN_LICENSESWIPE (FLDNUM) 96
#define FN_BANKNUMBER (FLDNUM) 97
#define FN_BANKACCOUNT (FLDNUM) 98
#define FN_KWMERCHANTRECORD (FLDNUM) 99
#define FN_SPOUSESSN (FLDNUM) 100
#define FN_SPOUSENAME (FLDNUM) 101
#define FN_SPOUSESALARY (FLDNUM) 102
#define FN_SPOUSEEMPLOYERPHONE (FLDNUM) 103
#define FN_SPOUSEEMPLOYERADR3 (FLDNUM) 104
#define FN_SPOUSEEMPLOYERADR2 (FLDNUM) 105
#define FN_SPOUSEEMPLOYERADR1 (FLDNUM) 106
#define FN_SPOUSEEMPLOYERNAME (FLDNUM) 107
#define FN_SALARY (FLDNUM) 108
#define FN_EMPLOYERPHONE (FLDNUM) 109
#define FN_EMPLOYERADR3 (FLDNUM) 110
#define FN_EMPLOYERADR2 (FLDNUM) 111
#define FN_EMPLOYERADR1 (FLDNUM) 112
#define FN_EMPLOYERNAME (FLDNUM) 113
#define FN_VEHICLEVALUE (FLDNUM) 114
#define FN_SPOUSEINFO (FLDNUM) 115
#define FN_POSITION         (FLDNUM) 116
#define FN_HOLDCHECKAMOUNT2 (FLDNUM) 117
#define FN_HOLDCHECKAMOUNT3 (FLDNUM) 118
#define FN_HOLDCHECKAMOUNT4 (FLDNUM) 119
#define FN_TIMESTAMP2            (FLDNUM) 120
#define FN_HOLDCHECKAPPROVALNUM2 (FLDNUM) 121
#define FN_HOLDCHECKAPPROVALNUM3 (FLDNUM) 122
#define FN_HOLDCHECKAPPROVALNUM4 (FLDNUM) 123
#define FN_PREAUTHFLAG (FLDNUM) 124
#define FN_DBKEYINFO (FLDNUM) 125
#define FN_OPERATORID (FLDNUM) 126
#define FN_DATE (FLDNUM) 127
#define FN_TIME (FLDNUM) 128
#define FN_HOLDCHECKCHECKNUM2 (FLDNUM) 130
#define FN_HOLDCHECKCHECKNUM3 (FLDNUM) 131
#define FN_HOLDCHECKCHECKNUM4 (FLDNUM) 132
#define FN_SPOUSEPOSITION (FLDNUM) 133
#define FN_YEARSEMPLOYED (FLDNUM) 134
#define FN_SPOUSEYEARSEMPLOYED (FLDNUM) 135
#define FN_HOLDCHECKAMOUNT1 (FLDNUM) 136
#define FN_HOLDCHECKCHECKNUM1 (FLDNUM) 137
#define FN_HOLDCHECKAPPROVALNUM1 (FLDNUM) 138
#define FN_HOLDCHECKSOURCETYPES (FLDNUM) 139
#define FN_POSITIVERULESRECORD (FLDNUM) 140
#define FN_POSITIVEFILERECORD (FLDNUM) 141
#define FN_POSITIVEFILESTATUS (FLDNUM) 142
#define FN_BANKPHONERECORD (FLDNUM) 143
#define FN_FINANCEAMOUNT (FLDNUM) 144
#define FN_PRODUCTADJUSTMENTS (FLDNUM) 145
#define FN_SSNSCORE (FLDNUM) 146
#define FN_EMPLOYERPHONEGOOD (FLDNUM) 147
#define FN_CONSUMERPHONEGOOD (FLDNUM) 148
#define FN_TRANSACTIONSCORE (FLDNUM) 149
#define FN_COMMENTS (FLDNUM) 150
#define FN_MOTHERSNAME (FLDNUM) 151
#endif
