#ifndef __BANKVERIFY_H
#define __BANKVERIFY_H
#define BVSTATUS_NOTVERIFIED       "NV"
#define BVSTATUS_UNVERIFIABLE      "UV"
#define BVSTATUS_ACCOUNTCLOSED     "AC"
#define BVSTATUS_NOTENOUGHMONEY    "IF"
#define BVSTATUS_VERIFIEDGOOD      "VG"
#endif
