 del C:\sps\source\classlib\WIN4ME.CSM
 del C:\sps\source\IPCShell\WIN4ME.CSM
 del C:\sps\source\lib\splib.csm
 del C:\sps\source\LogSearch\LogSearch.csm
 del C:\sps\source\MsgBox\msgbox.csm
 del C:\sps\source\NetRoute\whello.csm
 del C:\sps\source\PosAuth\SERVERAPP.CSM
 del C:\sps\source\ReferQue\WIN4ME.CSM
 del C:\sps\source\SPSFile\PosFileMan.csm
 del C:\sps\source\SPSManager\WIN4ME.CSM
 del C:\sps\source\Utilities\kdstest\KDSTest.csm
 del C:\sps\source\Utilities\PosTest\Kwtest.csm
 del C:\sps\source\VoiceAuth\AddProgramItem.csm
 del C:\sps\source\VoiceAuth\CheckAuth.csm
 del C:\sps\source\VoiceAuth\RegSetup.csm

